var annotated_dup =
[
    [ "APatternMesh", "classAPatternMesh.html", null ],
    [ "FCanvasAssetManager", "classFCanvasAssetManager.html", "classFCanvasAssetManager" ],
    [ "FCanvasAssets", "classFCanvasAssets.html", null ],
    [ "FCanvasInputHandler", "classFCanvasInputHandler.html", "classFCanvasInputHandler" ],
    [ "FCanvasMesh", "classFCanvasMesh.html", "classFCanvasMesh" ],
    [ "FCanvasPaint", "classFCanvasPaint.html", "classFCanvasPaint" ],
    [ "FCanvasPatternMerge", "classFCanvasPatternMerge.html", "classFCanvasPatternMerge" ],
    [ "FCanvasSewing", "classFCanvasSewing.html", "classFCanvasSewing" ],
    [ "FCanvasState", "structFCanvasState.html", "structFCanvasState" ],
    [ "FCanvasUtils", "classFCanvasUtils.html", null ],
    [ "FClickTarget", "structFClickTarget.html", "structFClickTarget" ],
    [ "FClothDesignCommands", "classFClothDesignCommands.html", null ],
    [ "FClothDesignModule", "classFClothDesignModule.html", null ],
    [ "FClothDesignStyle", "classFClothDesignStyle.html", null ],
    [ "FClothDesignToolkit", "classFClothDesignToolkit.html", "classFClothDesignToolkit" ],
    [ "FClothPhysicalConfig", "structFClothPhysicalConfig.html", null ],
    [ "FClothSimSettings", "structFClothSimSettings.html", null ],
    [ "FCurvePointData", "structFCurvePointData.html", null ],
    [ "FEdgeIndices", "structFEdgeIndices.html", "structFEdgeIndices" ],
    [ "FLoadedShapeData", "structFLoadedShapeData.html", "structFLoadedShapeData" ],
    [ "FPatternSewingConstraint", "structFPatternSewingConstraint.html", null ],
    [ "FPresetItem", "structFPresetItem.html", null ],
    [ "FSeamDefinition", "structFSeamDefinition.html", "structFSeamDefinition" ],
    [ "FShapeData", "structFShapeData.html", null ],
    [ "SClothDesignCanvas", "classSClothDesignCanvas.html", null ],
    [ "UClothDesignEditorMode", "classUClothDesignEditorMode.html", null ],
    [ "UClothShapeAsset", "classUClothShapeAsset.html", null ]
];