var annotated_dup =
[
    [ "APatternMesh", "classAPatternMesh.html", null ],
    [ "FCanvasAssetManager", "structFCanvasAssetManager.html", null ],
    [ "FCanvasAssets", "structFCanvasAssets.html", null ],
    [ "FCanvasInputHandler", "structFCanvasInputHandler.html", null ],
    [ "FCanvasMesh", "structFCanvasMesh.html", null ],
    [ "FCanvasPaint", "structFCanvasPaint.html", null ],
    [ "FCanvasPatternMerge", "structFCanvasPatternMerge.html", null ],
    [ "FCanvasSewing", "classFCanvasSewing.html", null ],
    [ "FCanvasState", "structFCanvasState.html", null ],
    [ "FCanvasUtils", "structFCanvasUtils.html", null ],
    [ "FClickTarget", "structFClickTarget.html", null ],
    [ "FClothDesignCommands", "classFClothDesignCommands.html", null ],
    [ "FClothDesignModule", "classFClothDesignModule.html", "classFClothDesignModule" ],
    [ "FClothDesignStyle", "classFClothDesignStyle.html", null ],
    [ "FClothDesignToolkit", "classFClothDesignToolkit.html", "classFClothDesignToolkit" ],
    [ "FClothPhysicalConfig", "structFClothPhysicalConfig.html", null ],
    [ "FClothSimSettings", "structFClothSimSettings.html", null ],
    [ "FCurvePointData", "structFCurvePointData.html", null ],
    [ "FEdgeIndices", "structFEdgeIndices.html", null ],
    [ "FLoadedShapeData", "structFLoadedShapeData.html", null ],
    [ "FPatternSewingConstraint", "structFPatternSewingConstraint.html", null ],
    [ "FPresetItem", "structFPresetItem.html", null ],
    [ "FSeamDefinition", "structFSeamDefinition.html", null ],
    [ "FShapeData", "structFShapeData.html", null ],
    [ "SClothDesignCanvas", "classSClothDesignCanvas.html", null ],
    [ "UClothDesignEditorMode", "classUClothDesignEditorMode.html", "classUClothDesignEditorMode" ],
    [ "UClothShapeAsset", "classUClothShapeAsset.html", null ]
];